CREATE SCHEMA PLATFORMA_CONCEDII;

USE PLATFORMA_CONCEDII;

CREATE TABLE USERS (

	ID INT PRIMARY KEY AUTO_INCREMENT,
    USER_NAME VARCHAR(45),
    PASSWORD VARCHAR(45),
    FIRST_NAME VARCHAR(45),
    LAST_NAME VARCHAR(45),
    MANAGER_ID INT,
	USER_ROLE VARCHAR(45)

);

CREATE TABLE HOLIDAYS (

	ID INT PRIMARY KEY AUTO_INCREMENT,
    START_DATE DATE,
    END_DATE DATE,
    USER_ID INT,
    STATUS VARCHAR(45)

);
